# Generated by Django 6.0.2 on 2026-02-25 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('origination_state', models.CharField(max_length=2)),
                ('vehicle_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Van', 'Van'), ('Other', 'Other')], max_length=16)),
                ('max_detour_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('pickup_radius_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('preferred_pickup_spot', models.CharField(blank=True, max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('quiet_ride', models.BooleanField(default=False)),
                ('music_ok', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origination', models.CharField(max_length=64)),
                ('destination_city', models.CharField(max_length=64)),
                ('destination_state', models.CharField(max_length=2)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('taking_passengers', models.BooleanField(default=False)),
                ('seats_available', models.PositiveIntegerField(default=0)),
                ('max_detour_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('pickup_radius_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('preferred_pickup_spot', models.CharField(blank=True, max_length=64)),
                ('estimated_total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('quiet_ride', models.BooleanField(default=False)),
                ('music_ok', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='rides.profile')),
            ],
        ),
    ]
