# Generated by Django 6.0.2 on 2026-02-25 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_profile_user_onetoone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RidePassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_rides', to='rides.profile')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='rides.ride')),
            ],
            options={
                'unique_together': {('ride', 'profile')},
            },
        ),
    ]
