# Generated by Django 6.0.2 on 2026-03-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_ridepassenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ride_type',
            field=models.CharField(choices=[('own_car', 'I have a car'), ('car_rental_group', 'Renting a car together')], default='own_car', max_length=20),
        ),
    ]
